FROM cidana/androidsdk:29.r10e
# Install cmake
USER root
#  --build-arg SSH_PRIVATE_KEY="$(cat /home/cidana/.ssh/id_rsa)" 
ARG SSH_PRIVATE_KEY
ARG SSH_PUBLIC_KEY
RUN apt update -qq && \
    apt install -y git && \
    apt -y install g++ && \
    apt -y install build-essential && \
    apt install -y curl  openssh-server && \
    wget https://cmake.org/files/v3.10/cmake-3.10.0-rc1.tar.gz && \
    tar -zxf cmake-3.10.0-rc1.tar.gz && \
    cd cmake-3.10.0-rc1 && \
    ./configure && \
    make && \
    make install && \
    cmake --version && \
    cd .. && \
    rm cmake-3.10.0-rc1.tar.gz && \
    mkdir /root/.ssh && \
    echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa && \
    echo "${SSH_PUBLIC_KEY}" > /root/.ssh/id_rsa_pub && \
    chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa_pub && \
    touch /root/.ssh/known_hosts && \
    git config --global user.email "foch.qu@cidana.com" && \
    git config --global user.name "foch.qu" && \
    echo "Host 192.168.0.234\n\tPasswordAuthentication no\n" >> /root/.ssh/config && \
    chmod 600 /root/.ssh/config && \
    ssh-keyscan 192.168.0.234 >> /root/.ssh/known_hosts && \
    ssh -Tv git@192.168.0.234 && \
# Install gitlab-runner
    curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 && \
    chmod +x /usr/local/bin/gitlab-runner && \
    mkdir /gitlab-runner && \
    gitlab-runner install --user=root --working-directory=/gitlab-runner && \
    gitlab-runner start && \
    apt-get clean
