FROM ubuntu:18.04
USER root
Run apt -qqy update && apt -qqy install make \
    gcc \
    g++ \
    curl \
    git  
RUN  curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 && \
     chmod +x /usr/local/bin/gitlab-runner && \
     mkdir /gitlab-runner && \
     gitlab-runner install --user=root --working-directory=/gitlab-runner && \
     gitlab-runner start && \
     apt clean all
